sudo: required
services:
  - docker
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
before_install:
  - docker pull wala/golang-otto
script:
  - yarn test
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
